#!/usr/bin/env bash
#
# Ensures that any Kubernetes cluster is cleaned up
#
set -euo pipefail

if ! test -f k8test/cluster/inventory.yml; then
  exit 0
fi

k8test/playbooks/destroy-cluster.yml -i k8test/cluster/inventory.yml
