#!/usr/bin/env bash
#
# Ensures that any Kubernetes cluster is cleaned up
#
set -euo pipefail

export CLUSTER_PREFIX="${CLUSTER_PREFIX-k8test}"

# Make sure the k8test/helpers/release-set CLI is available
source helpers/run-in-test-cluster
ensure-k8test > /dev/null

k8test/playbooks/destroy-cluster.yml \
  -i k8test/cluster/inventory.yml \
  -e cluster_prefix="$CLUSTER_PREFIX"
