#!/usr/bin/env bash
set -euo pipefail

# Read explicit Kubernetes versions from config
K8S_VERSIONS=$(jq -r '.versions' .github/kubernetes-versions.json)

# Returns the matrix entry for the given index (1-n)
function matrixentry {
  # Kubernetes releases
  echo "$K8S_VERSIONS" | jq -r ".[$(( $1 - 1 ))]"

  # The the private subnet range
  echo "10.100.$1.0/24"

  # A semi-preditable cluster prefix (we want to reuse them across jobs, but
  # not inside a job). Reuse allows us to ensure that the cleanup process
  # at the beginning of a test will remove old runs.
  echo "k8test-matrix-$1"
}

function matrixobject {
  matrixentry "$1" | jq --raw-input --null-input --compact-output '{
    "kubernetes": inputs,
    "subnet": inputs,
    "cluster_prefix": inputs,
  }'
}

function matrixentries {
  matrixobject 1
  matrixobject 2
  matrixobject 3
}

function matrixobjects {
  matrixentries | jq --null-input --compact-output '[inputs]'
}

matrixobjects
