version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - lll
    - makezero
    - staticcheck
    - unparam
    - unused
    - wrapcheck
  settings:
    lll:
      line-length: 80
      tab-width: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: .+LoadBalancer|// http(s)://
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
