version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - gomoddirectives
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nilnil
    - noctx
    - nonamedreturns
    - revive
    - testifylint
    - testpackage
    - varnamelen
    - usestdlibvars
    - whitespace
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: .+LoadBalancer|// http(s)://
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
