name: Tests

on:
  push:
    branches:
      - main
  pull_request:

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: 1.21

jobs:
  lint:
    name: "Run Linters"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
          key: lint-${{ hashFiles('go.mod') }}

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.6

      - name: Run Linter
        run: make lint

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
          key: lint-${{ hashFiles('go.mod') }}

  unit:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Run Unit Tests
        run: make test

  supported-releases:
    name: "Get Kubernetes Releases"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "List supported releases"
        id: list
        run: 'echo "releases=$(helpers/supported-releases)" >> $GITHUB_OUTPUT'

    outputs:
      releases: ${{ steps.list.outputs.releases }}

  integration:
    name: "Kubernetes ${{ matrix.kubernetes }}"
    runs-on: ubuntu-latest

    needs:
      - lint
      - unit
      - supported-releases

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        kubernetes: "${{ fromJson(needs.supported-releases.outputs.releases) }}"

    env:
      CLOUDSCALE_API_TOKEN: ${{ secrets.CLOUDSCALE_API_TOKEN }}
      KUBERNETES: '${{ matrix.kubernetes }}'

    # Prevent integration tests from running in parallel. Ideally this should
    # be seuqential, but that won't work due to the following issue:
    #
    # https://github.com/orgs/community/discussions/5435
    #
    # Instead we ensure that only one integration test per supported version
    # is run at any given time.
    concurrency:
      group: integration-${{ matrix.kubernetes }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Generate cluster prefix
        run: echo CLUSTER_PREFIX="k8test-$(uuidgen | cut -d '-' -f 1)" >> $GITHUB_ENV

      - name: Create Test Cluster
        run: helpers/run-in-test-cluster

      - name: Wait For CCM Startup
        run: sleep 60

      - name: Run Integration Tests
        run: make integration

      - name: Destroy Test Cluster
        if: always()
        run: helpers/cleanup
