name: Tests
on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
