name: Tests
on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.5

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
