name: Validate GitHub Workflows

permissions: {}

on:
  push:
    branches: [main]
    paths: ['.github/**']
  pull_request:
    paths: ['.github/**']

jobs:
  validate:
    permissions:
      contents: read
      security-events: write
    name: Run zizmor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
